# Generated by Django 3.1 on 2020-09-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20200901_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='Academic',
            new_name='Academic_Acreditation',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='Acreditation',
        ),
    ]
