# Generated by Django 3.1 on 2020-09-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20200901_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='LinkedIn',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='Mobile',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='Office',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='LinkedIn_address',
            field=models.URLField(blank=True, verbose_name='LinkedIn address'),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='Mobile_Phone',
            field=models.IntegerField(default=0, verbose_name='Mobile Phone'),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='Office_Phone',
            field=models.IntegerField(default=0, verbose_name='Office Phone'),
        ),
    ]
