# Generated by Django 3.1 on 2020-09-01 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(choices=[('1', 'Mr'), ('2', 'Mrs'), ('3', 'Miss'), ('4', 'Dr'), ('5', 'Prof')], default=('1', 'Mr'), max_length=1)),
                ('Profession', models.CharField(blank=True, max_length=128)),
                ('Academic', models.CharField(blank=True, max_length=128)),
                ('Acreditation', models.CharField(blank=True, max_length=128)),
                ('Institution', models.CharField(blank=True, max_length=128)),
                ('Office', models.IntegerField(default=0)),
                ('Phone', models.IntegerField(default=0)),
                ('Mobile', models.IntegerField(default=0)),
                ('Address', models.CharField(blank=True, max_length=128)),
                ('LinkedIn', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
