# Generated by Django 3.1 on 2020-09-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200901_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='LinkedIn_address',
            field=models.URLField(blank=True, verbose_name='LinkedIn address'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='Mobile_Phone',
            field=models.IntegerField(default=0, verbose_name='Mobile Phone'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='Office_Phone',
            field=models.IntegerField(default=0, verbose_name='Office Phone'),
        ),
    ]
