# Generated by Django 3.1 on 2020-09-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20200901_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='Office_Phone',
            field=models.CharField(max_length=20, verbose_name='Office Phone'),
        ),
    ]
